
pagination:
  items_per_page: 10
  first_page: 1

ingredient:
  no_quantity_unit_id: 17

limits:
  max_total_items: 20
  min_serving_size: 1
  default_serving_size: 1
  default_max_serving_size: 35
  min_items_to_process: 1
  min_items_to_decrement: 1
  unique_unit_id_threshold: 1

confirmation:
  token_validity_hours: 24

cart:
  default_item_count_decrement: 1