
pagination:
  items_per_page: 10
  first_page: 1

ingredient:
  no_quantity_unit_id: 17

limits:
  max_total_items: 20
  min_serving_size: 1
  default_serving_size: 1
  default_max_serving_size: 10
  min_items_to_process: 1
  min_items_to_decrement: 1
  unique_unit_id_threshold: 1
  max_quantity_value: 999
  max_integer_digits: 3
  max_decimal_places: 1

confirmation:
  token_validity_hours: 24

cart:
  default_item_count_decrement: 1

recipe_step:
  initial_step_order: 0
  step_order_increment: 1

recipe_step_categories:
  vegetable_prep: 1
  meat_prep: 2
  other_prep: 3